apiVersion: apps/v1
kind: Deployment
metadata:
  name:  stage-cloud-gateway
  namespace: zipy-stage
  labels:
    app:  stage-cloud-gateway
spec:
  selector:
    matchLabels:
      app: stage-cloud-gateway
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app:  stage-cloud-gateway
    spec:
      restartPolicy: Always
      containers:
      - name:  stage-cloud-gateway
        image:  gcr.io/zipydev/stage-cloud-gateway:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8989
          initialDelaySeconds: 120
          periodSeconds: 5
          # successThreshold: 1
          # failureThreshold: 3
          # timeoutSeconds: 1  
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8989
          initialDelaySeconds: 120
          periodSeconds: 5
          # successThreshold: 1
          # failureThreshold: 3
          # timeoutSeconds: 1
        ports:
        - name: http
          containerPort: 8989
        resources:
          requests:
            cpu: 150m
            memory: 300Mi
          limits:
            cpu: 200m
            memory: 500Mi

---
apiVersion: v1
kind: Service
metadata:
  name: stage-cloud-gateway
  namespace: zipy-stage
spec:
  selector:
    app: stage-cloud-gateway
  type: ClusterIP
  ports:
  - name: stage-cloud-gateway
    protocol: TCP
    port: 8989
    targetPort: 8989

# ---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: dev-divolte-auto-scale
#   namespace: zipy-stage
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: dev-customer-service
#   minReplicas: 1
#   maxReplicas: 3
#   targetCPUUtilizationPercentage: 50